version: '2'
#please note the complex links and affinity system to control the startup order
#required to get the backup container on another host different from the db.
services:
    dbdata:
        image: postgres:9.5
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
    db:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: dbdata
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes_from:
            - dbdata
    odoodata:
        image: adhoc/odoo-ar:9.0
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
            - /opt/odoo/data
            - /opt/odoo/custom-addons
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: odoodata
            io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=$${stack_name}/db
        external_links:
            - base/aeroo-docs:aeroo
        links:
            - db:db
        volumes_from:
            - odoodata
        environment:
            - VIRTUAL_HOST=$strVirtualHostProd
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0
    dbdata-backup:
        image: million12/ssh
        labels:
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/db
        links:
            - db:db

