.catalog:
  name: "AOH Odoo9 Simple SSB"
  version: "SideKickStorageAndBackup"
  description: "AdHoc Odoo Hosting (AOH) single Odoo stack w/sidekick storage and a safety remote backup"
  uuid: ingadhoc-odoo9ssb
  minimum_rancher_version: v1.1.4
  questions:
    - variable: strVirtualHostProd
      label: "Odoo Production DNS Hostname"
      description: "The DNS hostname. Used by any DNS agents and by http proxies. E.g. myapp0.domain.io"
      type: "string"
      required: true
      default: "{io.rancher.stack.name}"
    - variable: strDatabase
      description: "The Odoo PostgreSQL database to be created on deploy"
      label: "Initial Odoo DB Name"
      type: "string"
      required: true
      default: "default"
    - variable: strBackupOptions
      description: "Backup options. E.g. --backupcron=(1 4 * * *)"
      label: "Optional backup options"
      type: "string"
      required: false
      default: ""
