name: AOH Base
description: |
  20170117002 AdHoc Odoo Hosting (AOH) system base stack. 
  Installs Aeroo Docs, Nginx automated proxy, Postfix automated incoming mail frontend.
version: 20170117002
category: ERP
