name: AOH Base
description: |
  AdHoc Odoo Hosting (AOH) system base stack. You need to install
  this stack on every rancher host that will provide AdHoc Odoo Hosting services.
version: 20161223003
category: ERP
