version: '2'
services:
    dbdata-prod-backup:
        image: million12/ssh
        labels:
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    dbdata-prod:
        image: postgres:9.5
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
    db-prod:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: dbdata-prod
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes_from:
            - dbdata-prod
    odoodata-prod:
        image: adhoc/odoo-ar:9.0
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
            - /opt/odoo/data
            - /opt/odoo/custom-addons
    odoo-prod:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: odoodata-prod
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        external_links:
            - aeroo-docs:aeroo
        links:
            - db-prod:db
        volumes_from:
            - odoodata-prod
        environment:
            - VIRTUAL_HOST=$strVirtualHostProd
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

    dbdata-test:
        image: postgres:9.5
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
    db-test:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: dbdata-test
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes_from:
            - dbdata-test
    odoodata-test:
        image: adhoc/odoo-ar:9.0
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
            - /opt/odoo/data
            - /opt/odoo/custom-addons
    odoo-test:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: odoodata-test
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        external_links:
            - aeroo-docs:aeroo 
        links:
            - db-test:db
        environment:
            - VIRTUAL_HOST=$strVirtualHostTest
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0
        volumes_from:
            - odoodata-test

    dbdata-train:
        image: postgres:9.5
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
    db-train:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: dbdata-train
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes_from:
            - dbdata-train
    odoodata-train:
        image: adhoc/odoo-ar:9.0
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
            - /opt/odoo/data
            - /opt/odoo/custom-addons
    odoo-train:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
            io.rancher.sidekicks: odoodata-train
            io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=$${stack_name}
        external_links:
            - aeroo-docs:aeroo 
        links:
            - db-train:db
        environment:
            - VIRTUAL_HOST=$strVirtualHostTrain
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0
        volumes_from:
            - odoodata-train

