.catalog:
  name: "AOH Odoo9 Simple SSB"
  version: "SSB+HealthChecks"
  description: "AdHoc Odoo Hosting (AOH) single Odoo stack w/sidekick storage and backup. Plus health checks."
  uuid: ingadhoc-odoo9ssbh
  minimum_rancher_version: v1.3.2
  questions:
    - variable: strVirtualHostProd
      label: "Odoo Production DNS Hostname"
      description: "The DNS hostname. Used by any DNS agents and by http proxies. E.g. myapp0.domain.io"
      type: "string"
      required: true
      default: "{io.rancher.stack.name}"
    - variable: strDatabase
      description: "The Odoo PostgreSQL database to be created on deploy"
      label: "Initial Odoo DB Name"
      type: "string"
      required: true
      default: "default"
    - variable: strBackupOptions
      description: "Backup options. E.g. --backuptype=[daily,weekly,monthly,warmcopy] --backuptime=4am --warmbackupfreq=15m"
      label: "Optional backup options"
      type: "string"
      required: false
      default: ""
#scaling and health checks per service as per docker-compose.yml
version: 2
services:
  odoo:
    scale: 1
    health_check:
      port: 8069
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  odoo-copy:
    scale: 1
    health_check:
      port: 8069
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  db:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  db-copy:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

