version: '2'
services:
    dbdata:
        image: postgres:9.5
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
    db:
        image: postgres:9.5
        labels:
            io.rancher.sidekicks: dbdata
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes_from:
            - dbdata
    odoodata:
        image: adhoc/odoo-ar:9.0
        entrypoint: /bin/bash
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
            - /opt/odoo/data
            - /opt/odoo/custom-addons
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.sidekicks: odoodata
            io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=$${stack_name}/db
        external_links:
            - aeroo-docs:aeroo 
        environment:
            - VIRTUAL_HOST=$strVirtualHost
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0
        volumes_from:
            - odoodata
        links:
            - db:db

