    db:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data:/var/lib/postgresql/data
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        volumes:
            - custom-addons:/opt/odoo/custom-addons
            - odoo_data:/opt/odoo/data
        environment:
            - VIRTUAL_HOST=$strVirtualHost
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0
#strVirtualHost is set via rancher-compose.yml variable
#the second virtual port is the chat/IM port
