    db:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - /var/lib/postgresql/data
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        volumes:
            - /opt/odoo/custom-addons
            - /opt/odoo/data
        environment:
            - VIRTUAL_HOST=$strVirtualHost
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

#environtment: comments
#the second virtual port is the chat/IM port
