.catalog:
  name: "AOH Odoo9 Simple Data Containers"
  version: "SidekickDataStorage"
  description: "AdHoc Odoo Hosting (AOH) system Odoo 9.0 w/sidekick data containers"
  uuid: ingadhoc-odoo9s
  minimum_rancher_version: v1.1.4
  questions:
    - variable: strVirtualHostProd
      label: "Odoo Production DNS Hostname"
      description: "The DNS hostname. Used by any DNS agents and by http proxies. E.g. myapp0.domain.io. The default uses the stack name."
      type: "string"
      required: true
      default: "{io.rancher.stack.name}"
    - variable: strDatabase
      description: "The Odoo PostgreSQL database to be created on deploy"
      label: "Initial Odoo DB Name"
      type: "string"
      required: true
      default: "default"
    
