version: 2
catalog:

  name: "AdHoc Odoo Stack"

  version: "1.0.0-rancher"

  description: "AdHoc Odoo Hosting (AOH) single Odoo stack w/sidekick storage and backup. Plus health checks and alternate server names. Has new configuration items."

  minimum_rancher_version: v1.3.2

  questions:

    - variable: strVirtualHostProd
      label: "Odoo Production DNS Hostname"
      description: "The DNS hostname. Used by any DNS agents and by http proxies. E.g. myapp0.domain.io"
      type: "string"
      required: true
      default: "{io.rancher.stack.name}"

    - variable: strOdooPassword
      label: "Odoo ADMIN_PASSWORD"
      description: "Odoo ADMIN_PASSWORD environment var"
      type: "string"
      required: true
      default: "admin"

    - variable: strDatabase
      label: "Initial Odoo DB Name"
      description: "The Odoo PostgreSQL database to be created on deploy"
      type: "string"
      required: true
      default: "default"

    - variable: strServerMode
      label: "Odoo SERVER_MODE"
      description: "Odoo SERVER_MODE environment var"
      type: "string"
      required: false
      default: ""

    - variable: intWorkers
      label: "Odoo WORKERS"
      description: "Odoo WORKERS environment var"
      type: "int"
      required: true
      default: "0"

    - variable: boolWithoutDemo
      label: "Odoo WITHOUT_DEMO"
      description: "Odoo WITHOUT_DEMO environment var"
      type: "boolean"
      required: true 
      default: True

    - variable: strBackupOptions
      label: "Optional backup options"
      description: "Backup options. E.g. --backupcron=(1 4 * * *)"
      type: "string"
      required: false
      default: "--backupcron=(12 3 * * *)"

    - variable: cOtherServerNames
      label: "Optional server names for nginx"
      description: "A semicolon (;) separated and terminated list of max 8 domain names for alternate access to Odoo instance. E.g. ourodoo.acme.com;www.acme.org;"
      type: "string"
      required: false
      default: ""

#scaling and health checks per service as per docker-compose.yml
services:
  odoo:
    scale: 1
    health_check:
      port: 8069
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  odoo-backup:
    scale: 1
    health_check:
      port: 8069
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  db:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  db-backup:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

