.catalog:
  name: "AOH Odoo9 Simple"
  version: "20161205002"
  description: "AdHoc Odoo Hosting (AOH) system simple Odoo 9.0 stack. Provides a production Odoo instance."
  uuid: ingadhoc-odoo9s
  minimum_rancher_version: v1.1.4
  questions:
    - variable: VIRTUAL_HOST
      description: "The DNS hostname for the Odoo portal"
      label: "DNS Hostname"
      type: "string"
      required: true
      default: "odoo0.localhost"
