    db:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data_prod:/var/lib/postgresql/$strVirtualHostProd/data
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db:db
        volumes:
            - custom-addons:/opt/odoo/$strVirtualHostProd/custom-addons
            - odoo_data:/opt/odoo/$strVirtualHostProd/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostProd
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

    db-test:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data_test:/var/lib/postgresql/$strVirtualHostTest/data
    odoo-test:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db-test:db
        volumes:
            - custom-addons:/opt/odoo/$strVirtualHostTest/custom-addons
            - odoo_data:/opt/odoo/$strVirtualHostTest/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostTest
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

    db-train:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data_train:/var/lib/postgresql/$strVirtualHostTrain/data
    odoo-train:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db-train:db
        volumes:
            - custom-addons:/opt/odoo/$strVirtualHostTrain/custom-addons
            - odoo_data:/opt/odoo/$strVirtualHostTrain/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostTrain
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

