    db:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data/$strVirtualHostProd/data:/var/lib/postgresql/data
    odoo:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db:db
        volumes:
            - custom-addons/$strVirtualHostProd/custom-addons:/opt/odoo/custom-addons
            - odoo_data/$strVirtualHostProd/data:/opt/odoo/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostProd
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

    db-test:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data/$strVirtualHostTest/data:/var/lib/postgresql/data
    odoo-test:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db-test:db
        volumes:
            - custom-addons/$strVirtualHostTest/custom-addons:/opt/odoo/custom-addons
            - odoo_data/$strVirtualHostTest/data:/opt/odoo/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostTest
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

    db-train:
        image: postgres:9.5
        labels:
            io.rancher.container.network: 'false'
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data/$strVirtualHostTrain/data:/var/lib/postgresql/data
    odoo-train:
        image: adhoc/odoo-ar:9.0
        labels:
            io.rancher.container.network: 'false'
        external_links:
            - aeroo-docs:aeroo
        links:
            - db-train:db
        volumes:
            - custom-addons/$strVirtualHostTrain/custom-addons:/opt/odoo/custom-addons
            - odoo_data/$strVirtualHostTrain/data:/opt/odoo/data
        environment:
            - VIRTUAL_HOST=$strVirtualHostTrain
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - ADMIN_PASSWORD=admin
            - WORKERS=0

