version: '2'
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            # - db_data:/var/lib/postgresql/data
            # TODO check if we use subdirectory as recommended here for GCE
            # https://hub.docker.com/_/postgres/
    odoo:
        image: ${strOdooImage}
        external_links:
            - base/aeroo-docs:aeroo
            - base/postfix-dockprox:smtp
        links:
            - db:db
        labels:
            - traefik.enable=stack
            - traefik.domain=juan.dev-adhoc.com
            - traefik.port=8069
            - traefik.alias.fqdn=$cOtherServerNames
        volumes:
            - odoo_data:/opt/odoo/data
        environment:
            - CREATE_DBNAME=$strDatabase
            - VIRTUAL_PORT=8069,8072
            - ODOO_VERSION=9.0
            - SERVER_MODE=$strServerMode
            - WORKERS=$intWorkers
            - ADMIN_PASSWORD=$strAdminPassword
            - WITHOUT_DEMO=$boolWithoutDemo
            - SMTP_HOST=smtp
volumes:
    odoo_data:
        driver: rancher-nfs
        external: false
    db_data:
        driver: rancher-nfs
        external: false
