version: '2'
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            # TODO check if we use subdirectory as recommended here for GCE
            # https://hub.docker.com/_/postgres/
            - db_data:/var/lib/postgresql/data
    odoo:
        image: adhoc/odoo-ar-e:${strOdooVersion}
        external_links:
            - base/aeroo-docs:aeroo
            - base/postfix-dockprox:smtp
        links:
            - db:db
        # labels:
        #     - traefik.enable=stack
        #     - traefik.domain=juan.dev-adhoc.com
        #     - traefik.port=8069
        #     - traefik.alias.fqdn=$cOtherServerNames
        volumes:
            - odoo_data:/opt/odoo/data
        environment:
            # TODO remove or use
            # - SMTP_HOST=smtp
            # - WITHOUT_DEMO=$boolWithoutDemo
            # - VIRTUAL_PORT=8069,8072
            - MAIL_CATCHALL_DOMAIN={$service_name}.juans.dev-adhoc.com
            - CREATEDB=True
            - DATABASE=$strDatabase
            - SERVER_MODE=$strServerMode
            - WORKERS=$intWorkers
            - ADMIN_PASSWORD=$strAdminPassword
    nginx:
        image: adhoc/odoo-nginx
        # image: nginx
        links:
            - odoo:odoo
        labels:
            - traefik.enable=stack
            - traefik.domain=juan.dev-adhoc.com,juans.dev-adhoc.com
            - traefik.port=80
            - traefik.alias.fqdn=$cOtherServerNames
        # volumes:
        #     - nginx_conf:/etc/nginx/nginx.conf:ro
volumes:
    odoo_data:
        driver: rancher-nfs
        external: false
    db_data:
        driver: rancher-nfs
        external: false
    nginx_conf:
        driver: rancher-nfs
        external: true
