.catalog:
  name: "Portworx"
  version: "1.0.2-GA"
  description: "Portworx Container Defined Storage for Docker"
  uuid: 252665-pwx-1.0.2
  minimum_rancher_version: v0.56.0
  questions:
    - variable: cluster_token
      description: "Cluster token obtained via Lighthouse or your Portworx representative"
      label: "Cluster Token"
      type: "string"
      required: true
      default: ""

portworx:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  image: portworx/px-enterprise
  container_name: px
  ipc: host
  net: host
  privileged: true
  environment:
    CLUSTER_TOKEN: {cluster_token}
  volumes:
     - /dev:/dev
     - /usr/src:/usr/src
     - /run/docker/plugins:/run/docker/plugins
     - /var/lib/osd:/var/lib/osd:shared
     - /etc/pwx:/etc/pwx
     - /opt/pwx/bin:/export_bin:shared
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/cores:/var/cores
  command: -t ${cluster_token} -a -f -daemon
  scale: 1


