.catalog:
  name: "Portworx"
  version: "1.0.2-GA"
  description: "Portworx Container Defined Storage for Docker"
  uuid: 252665-pwx-1.0.2
  minimum_rancher_version: v0.56.0
  questions:
    - variable: cluster_token
      description: "Cluster token obtained via Lighthouse or your Portworx representative"
      label: "Cluster Token"
      type: "string"
      required: true
      default: ""

portworx:
  scale: 1
