.catalog:
  name: "Portworx"
  version: "1.0.2-GA"
  description: "Container Defined Storage for Docker"
  uuid: 252667-pwx-1.0.2
  minimum_rancher_version: v0.56.0
  questions:
    - variable: cluster_token
      description: "Cluster Token from Lighthouse"
      label: "Cluster Token"
      type: "string"
      required: true
      default: " "
