nginx-proxy:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: registry.unxs.io:5000/jwilder/nginx-proxy
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  stdin_open: true
aeroo-docs:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  image: registry.unxs.io:5000/adhoc/aeroo-docs
