nginx-dockprox:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: unxsio/nginx-dockprox
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
  stdin_open: true
aeroo-docs:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  image: adhoc/aeroo-docs
